### ISSUE TITLE
Overseer error

### ISSUE THREAD

**Issue by miguelangelcastellanos** [SVMP/svmp-overseer#12]
Hello, thanks for providing this application, any help will be appreciated.

When trying to use the svmp-config for the first time , the overseer crashes:

]**# svmp-config list**
Using overseer URL: https://xxx.xxx.xx:3000

Proxy users:
    Error code: 500, text: Internal Server Error

------------------------------------------------------------------
**# node server.js --config  config/config-local.yaml**

2018-06-26T12:45:07.235Z - info: Loading config file: config/config-local.yaml
2018-06-26T12:45:07.763Z - info: Mongoose:  connected to: mongodb://localhost/svmp_overseer_production_db
express-session deprecated undefined resave option; provide resave option lib/console/express.js:63:13
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option lib/console/express.js:63:13
2018-06-26T12:45:08.387Z - info: SVMP REST API running on port 3000 with SSL
TypeError: Cannot read property 'sub' of undefined
    at /software/svmp-overseer/lib/authentication.js:75:38
    at Object.module.exports.verify (/software/svmp-overseer/node_modules/jsonwebtoken/index.js:39:12)
    at Object.exports.checkAdminToken [as handle] (/software/svmp-overseer/lib/authentication.js:74:13)
    at next_layer (/software/svmp-overseer/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/software/svmp-overseer/node_modules/express/lib/router/route.js:107:5)
    at /software/svmp-overseer/node_modules/express/lib/router/index.js:205:24
    at Function.proto.process_params (/software/svmp-overseer/node_modules/express/lib/router/index.js:269:12)
    at next (/software/svmp-overseer/node_modules/express/lib/router/index.js:199:19)
    at next (/software/svmp-overseer/node_modules/express/lib/router/index.js:176:38)
    at next (/software/svmp-overseer/node_modules/express/lib/router/index.js:176:38)
    at Layer.handle (/software/svmp-overseer/app/routes/log.js:110:9)
    at trim_prefix (/software/svmp-overseer/node_modules/express/lib/router/index.js:240:15)
    at /software/svmp-overseer/node_modules/express/lib/router/index.js:208:9
    at Function.proto.process_params (/software/svmp-overseer/node_modules/express/lib/router/index.js:269:12)
    at next (/software/svmp-overseer/node_modules/express/lib/router/index.js:199:19)
    at SendStream.error (/software/svmp-overseer/node_modules/express/node_modules/serve-static/index.js:86:37)
2018-06-26T12:45:37.546Z - info: 74.50.112.144 - - "GET /services/users" 500 "-"

I guess this is related to the authentication toket, but I haven't find where to configure the token in the overseer.

Thanks a lot.

Miguel

**Comment by miguelangelcastellanos** [comment]
Solved, I was not putting the token correctly.

**Comment by Bobyuan1015** [comment]
how do you solve it ?
 I met the similar error.
I cannot run npm test succuessfully.
